version: '3.4'

services:
  patientsresolver.api:
    image: ${DOCKER_REGISTRY-}patientsresolverapi
    container_name: patientsresolver.api
    build:
      context: .
      dockerfile: src/Services/PatientsResolver.API/PatientsResolver.API/Dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq

  agents.api:
    image: ${DOCKER_REGISTRY-}agentsapi
    container_name: agents.api
    build:
      context: .
      dockerfile: src/Services/Agents.API/Agents.API/Dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq