version: '3.4'

services:
  patientsresolver.api: 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 8033:80
    networks:
        - aModelNetwork
    depends_on:
      - rabbitmq

  agents.api:
    ports:
      - 8002:80
    networks:
      - aModelNetwork
    depends_on:
      - rabbitmq

  parameters.api:
    ports:
      - 8003:80
    networks:
      - aModelNetwork

  envoygateway:
    ports:
        - "9901:9901"
        - "10000:10000"
    volumes:
        - ./src/ApiGateways/Envoy/envoy.yaml:/etc/envoy/envoy.yaml
    networks:
        - aModelNetwork

  rabbitmq:
    tty: true
    hostname: rabbitmq
    ports:
        - "15672:15672"
        - "5672:5672"
    environment:
        - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
        - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWD}
    networks:
        - aModelNetwork

  mongo:
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWD}
    volumes:
     - ./mongo:/data/db

volumes:
   db_volume:
   pgadmin:
   postgresData:
       external: true

networks:
    aModelNetwork:
        external: true