version: '3.4'

services:
  envoygateway:
    build:
      context: .
      dockerfile: src/ApiGateways/Envoy/Dockerfile
    ports:
      - "9901:9901"
      - "10000:10000"
    volumes:
      - ./src/ApiGateways/Envoy/envoy.yaml:/etc/envoy/envoy.yaml
    networks:
        - aModelNetwork

  rabbitmq:
    container_name: rabbitmq
    tty: true
    hostname: rabbitmq
    ports:
        - "15672:15672"
        - "5672:5672"
    image: rabbitmq:3-management
    environment:
        - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
        - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWD}
    networks:
        - aModelNetwork

  mongo:
    image: mongo:4.4.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWD}
    volumes:
     - ./mongo:/data/db

  patientsresolver.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      #- ASPNETCORE_URLS=https://+:443;http://+:80
      #- ASPNETCORE_HTTPS_PORT=8004
      #- ASPNETCORE_Kestrel__Certificates__Default__Password=lisa2021
      #- ASPNETCORE_Kestrel__Certificates__Default__Path=/https/localhost.pfx
    ports:
      - 8033:80
    networks:
        - aModelNetwork

  agents.api:
    ports:
      - 8002:80
    networks:
      - aModelNetwork

volumes:
   db_volume:
   pgadmin:
   postgresData:
       external: true

networks:
    aModelNetwork:
        external: true
    

