version: '3.4'

services:
  patientsresolver.api:
    image: ${DOCKER_REGISTRY-}patientsresolverapi
    container_name: patientsresolver.api
    build:
      context: .
      dockerfile: src/Services/PatientsResolver.API/PatientsResolver.API/Dockerfile
    restart: on-failure

  agents.api:
    image: ${DOCKER_REGISTRY-}agentsapi
    container_name: agents.api
    build:
      context: .
      dockerfile: src/Services/Agents.API/Agents.API/Dockerfile

  envoygateway:
    build:
        context: .
        dockerfile: src/ApiGateways/Envoy/Dockerfile

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management

  mongo:
    image: mongo:4.4.6
    restart: always