version: '3.4'

services:
  patientsresolver.api:
    image: ${DOCKER_REGISTRY-}patientsresolverapi
    build:
      context: .
      dockerfile: PatientsResolver.API/Dockerfile
    volumes:
      - "C:/Users/Lisovenko/Desktop/asp:/data"

  influencecalculator.api:
    image: ${DOCKER_REGISTRY-}influencecalculatorapi
    build:
      context: .
      dockerfile: InfluenceCalculator.API/Dockerfile

  patientdatahandler.api:
    image: ${DOCKER_REGISTRY-}patientdatahandlerapi
    build:
      context: .
      dockerfile: PatientDataHandler.API/Dockerfile

  rabbitmq:
    container_name: rabbitmq
    tty: true
    hostname: rabbitmq
    ports:
        - "15672:15672"
        - "5672:5672"
    image: rabbitmq:3-management
    environment:
        - RABBITMQ_DEFAULT_USER=user
        - RABBITMQ_DEFAULT_PASS=password

  postgres_image:
    image: postgres:latest
    restart: always
    ports:
        - "5432:5432"
    volumes:
         - db_volume:/var/lib/postgresql/data
    environment:
         POSTGRES_USER: "postgres"
         POSTGRES_PASSWORD: "lisa2021"
         POSTGRES_DB: "PatientData_db"
         PGDATA: "/var/lib/postgresql/data/pgdata"

    

